[project]
name = "chevstyle-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Malachi", email = "dminsalami@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
chevstyle-backend = "chevstyle_backend:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
